services:
  postgres:
    image: postgres
    container_name: newsapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: news
    ports:
      - "5431:5432"
    volumes:
      - news:/data/postgres
volumes:
  news:
